### PR TITLE
Changed install location from `/usr/` to correct `/usr/local/`.

### PR DESCRIPTION
**Pull request by alexreg**

### CODE REVIEW

**Comment by markcarver** [comment]
>     remote: ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory

`/usr/local` isn't where it's looking for the "program".

Besides, I'm not very interested in maintaining this project anymore and deprecating it in favor of: https://github.com/theseal/ssh-askpass
```bash
brew tap theseal/ssh-askpass
brew install ssh-askpass
```

**Comment by alexreg** [comment]
You should never install anything to `/usr/libexec`. This is considered system territory on OS X (and BSD), and indeed is blocked under the new System Integrity Protection policy in recent versions of OS X! `/usr/local/...` is meant for all installable stuff.

But fair enough if you're deprecating this project, I'll move over to the other recommended one. Cheers.

**Comment by markhalliwell** [comment]
I'm certainly well aware of what the directories are meant for. That is/was never the issue. `ssh-agent` looks for it at exactly this path: `/usr/libexec/ssh-askpass`... not anywhere else.

And yes, SIP makes it even more difficult to "install", but even creating a symlink (as the brew package suggests) still requires disabling SIP, "installing it" and then re-enabling SIP.

Short version: apple is turning over a new leaf and showing that it really hates power users. Nothing I, nor this project, can do about that. Hence why I'm deprecating it in favor or something that has better installation/instructions.

**Comment by markhalliwell** [comment]
Also, the other reason installing/symlinking it to `/usr/libexec/ssh-askpass` is because `export SSH_ASKPASS="/path/to/ssh-askpass"` doesn't always work like one would expect.

**Comment by jdwhite** [comment]
It’s annoying that Apple didn’t just patch ssh-agent to change the default path to ssh-askpass, but here’s what I do to work around the issue.

I got tired of dealing with symlinks, doing the temp disable SIP dance, and installing XQuartz just so DISPLAY got properly defined and came up with the following, which lives in my ~/.bashrc.

env_ssh_askpass="`/bin/launchctl getenv SSH_ASKPASS`"
if [ "x${env_ssh_askpass}" != “x/usr/local/libexec/ssh-askpass" ]; then
        /bin/launchctl setenv SSH_ASKPASS /usr/local/libexec/ssh-askpass
        env_display="`/bin/launchctl getenv DISPLAY`"
        if [ "x${env_display}" == "x" ]; then
                /bin/launchctl setenv DISPLAY bogon
        fi
        /usr/bin/killall -9 ssh-agent 2>&1 >/dev/null
fi

Since ssh-agent is spawned from launchd, we need to set SSH_ASKPASS and DISPLAY in launchd’s environment.  Once that’s done we kill ssh-agent so it will respawn with the updated SSH_ASKPASS and DISPLAY.  No symlinks, no rebooting twice to fiddle with SIP, no installing XQuartz.

-Jason

**Comment by alexreg** [comment]
Nice solution, @jdwhite. You should raise an issue on theseal/ssh-askpass and get this adopted as the official solution, if possible.

**Comment by alexreg** [comment]
Actually, it doesn't work for me unfortunately... I've confirmed the environment variables are set fine though.

**Pull request closed without merging**
